export const FETCH_TIREDETAILS_REQUEST = 'FETCH_TIREDETAILS_REQUEST'
export const FETCH_TIREDETAILS_SUCCESS = 'FETCH_TIREDETAILS_SUCCESS'
export const FETCH_TIREDETAILS_FAILURE = 'FETCH_TIREDETAILS_FAILURE'


